name: Kaggle Badges

on:
  schedule:
    # You can change the cron expression to suit your needs
    - cron: "30 19 5 * *" # 19:30 on the 5th of every month
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Puppeteer browser
        run: npx puppeteer browsers install chrome@126.0.6478.63

      - name: Use Kaggle Badges Action
        uses: spider-man-tm/kaggle-badges@v1.0.0
        with:
          user_name: ${{ secrets.KAGGLE_USERNAME }}

      - name: Commit and Push SVG files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add ./kaggle-badges/*
          git commit -m "Add generated SVG files" || echo "No changes to commit"
          git push
